In [12]:
#Numpy is help for process the numerical data sets like : list.
import numpy as np

list = np.array([1,2,3,4,5])

print(List)

[1 2 3 4 5]


In [13]:
#Copy the list 
list1 = np.copy(list)
print(List1)


[1 2 3 4 5]


In [14]:
#Verify max value in list
list1.max()

5

In [15]:
#Min value in list
list1.min()

1

In [16]:
#Avarage value in list:
list1.mean()

3.0

In [52]:
list3 = np.array([1,2,3])


In [53]:
#Max Index value in list
list3.argmax()

2

In [54]:
#min index value in list 
list3.argmin()

0

In [51]:
list3.argsort()

array([0, 1, 2], dtype=int64)

In [82]:
#Customer history 
customer_salary = np.array([60000])
debits_month = np.array([1000,2000,3000,5000,4000,3000,2000,1000,20,30,40,5000,3000,4000])
credits_month = np.array([2000,3000])
loans = np.array([14000, 9000,325, 290, 5400 ])
total_loan_amount = loans.sum()
total_debits_month = debits_month.sum()
total_expens = total_debits+total_loan_amount
customer_monthly_savings =  customer_salary-total_expens
print("total_loan_amount:",       total_loan_amount)
print("total_creditcard_debits:", total_debits)
print("total_expens:",            total_expens)
print("customer savings",          customer_monthly_savings)

total_loan_amount: 29015
total_creditcard_debits: 33090
total_expens: 62105
customer savings [-2105]


In [87]:
debits_month2 = np.array([1000,2000,4000,6000,4000,30,40,20])
loans_month2 = np.array([14000,9000,325,290,5400])
total_loan_amount_month2 = loans_month2.sum()
print("total_loan_amount_month2:", total_loan_amount_month2)

total_loan_amount_month2: 29015


In [90]:
customer_two_months_loan = np.add(total_loan_amount,total_loan_amount_month2)
customer_two_months_loan

58030

In [92]:
loan_pay_year = customer_two_months_loan * 6
loan_pay_year

348180

In [95]:
np.average(loan_pay_year)

348180.0

In [96]:
np.append(loans_month2,loans)

array([14000,  9000,   325,   290,  5400, 14000,  9000,   325,   290,
        5400])

In [105]:
two_months_debits = np.append(debits_month,debits_month2)

In [106]:
two_months_debits

array([1000, 2000, 3000, 5000, 4000, 3000, 2000, 1000,   20,   30,   40,
       5000, 3000, 4000, 1000, 2000, 4000, 6000, 4000,   30,   40,   20])

In [107]:
two_months_debits.sum()

50180

In [109]:
np.average(two_months_debits)

2280.909090909091

In [110]:
np.mean(two_months_debits)

2280.909090909091

In [112]:
np.median(two_months_debits)

2000.0

In [118]:
np.ndim(two_months_debits)

1