In [1]:
#Numpy: Numpy is numarical python, to perform the numerical operations we can use the numpy, 
#numpy wroks for list of values and data points, 
#numpy is fast and less memory of the data 

In [4]:
import numpy as np

In [5]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [6]:
np.arange(5) "arrange is the range function"

array([0, 1, 2, 3, 4])

In [8]:
np.arange(5,dtype = float)

array([0., 1., 2., 3., 4.])

In [9]:
np.arange(100,110)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [11]:
np.arange(100,120,2)

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118])

In [12]:
abc = np.array([1,4,10,19,20])

In [14]:
print(abc)

[ 1  4 10 19 20]


In [15]:
abc1 = (10,20,30,40)

In [16]:
np.array(abc1)

array([10, 20, 30, 40])

In [17]:
abc2 = {10,15,20,30}

In [18]:
np.array(abc2)

array({10, 20, 30, 15}, dtype=object)

In [19]:
abc3 = [10,20,30,"india"]

In [20]:
np.array(abc3)

array(['10', '20', '30', 'india'], dtype='<U11')

In [21]:
salary = np.array([10000,150000,20000,30000,400000])

In [22]:
len(salary)

5

In [23]:
expenses = np.array([5000,7000,8000,9000,10000])

In [24]:
len(expenses)

5

In [25]:
saving = salary-expenses

In [26]:
saving

array([  5000, 143000,  12000,  21000, 390000])

In [27]:
abc1 =[10,40,30,50]

In [28]:
abc1*3

[10, 40, 30, 50, 10, 40, 30, 50, 10, 40, 30, 50]

In [29]:
salary*3

array([  30000,  450000,   60000,   90000, 1200000])

In [30]:
salary/12

array([  833.33333333, 12500.        ,  1666.66666667,  2500.        ,
       33333.33333333])

In [33]:
perday = salary/12/30

In [35]:
perday

array([  27.77777778,  416.66666667,   55.55555556,   83.33333333,
       1111.11111111])

In [36]:
np.sqrt(salary)

array([100.        , 387.29833462, 141.42135624, 173.20508076,
       632.45553203])

In [42]:
np.exp(10)

22026.465794806718

In [38]:
np.exp(salary)

array([inf, inf, inf, inf, inf])

In [43]:
np.square(salary)

array([ 100000000, 1025163520,  400000000,  900000000, 1086210048],
      dtype=int32)

In [44]:
salary

array([ 10000, 150000,  20000,  30000, 400000])

In [45]:
10000*10000

100000000

In [46]:
salary = np.array([10000,15000,18000,20000,40000])

In [47]:
salary

array([10000, 15000, 18000, 20000, 40000])

In [48]:
salary.ndim

1

In [49]:
salary = np.array([[100,200,300,400]])

In [50]:
salary.ndim

2

In [51]:
salary = np.array([[[[10,20,30,40]]]])

In [52]:
salary.ndim

4

In [53]:
salary = np.array([[10,20,30,40,50],[15,25,35,45,55]])

In [54]:
salary.ndim

2

In [55]:
salary

array([[10, 20, 30, 40, 50],
       [15, 25, 35, 45, 55]])

In [56]:
salary.sum()

325

In [57]:
salary=np.array([10,20,30,40,50])

In [58]:
salary.ndim

1

In [59]:
salary.shape

(5,)

In [60]:
salary=np.array([[10,20,30,40,50],[60,70,80,90,100]])

In [62]:
salary.shape #Sahpe will display the dimention of the data, before (,) is rows and after (,) is clolumns

(2, 5)

In [63]:
salary = np.array([[10,20],[30,40]])

In [65]:
expenses = np.array([[1,2],[3,4]])

In [66]:
print(salary)

[[10 20]
 [30 40]]


In [67]:
print(expenses)

[[1 2]
 [3 4]]


In [68]:
salary+expenses

array([[11, 22],
       [33, 44]])

In [69]:
salary*expenses

array([[ 10,  40],
       [ 90, 160]])

In [70]:
np.dot(salary,expenses)

array([[ 70, 100],
       [150, 220]])

In [71]:
abc = [[10,20,30],[20,50,60]]

In [72]:
np.matrix(abc)

matrix([[10, 20, 30],
        [20, 50, 60]])

In [73]:
salary = [10,50,60,70,80,90]

In [74]:
abc = np.array(salary)

In [75]:
abc

array([10, 50, 60, 70, 80, 90])

In [77]:
abc1 = abc.reshape(2,3)

In [78]:
abc1.shape

(2, 3)

In [79]:
abc1

array([[10, 50, 60],
       [70, 80, 90]])

In [81]:
abc1.ndim

2

In [82]:
abc2 = np.array([10,20,30,40,50,60,70])

In [86]:
abc2.reshape(2,3) #"if leanth of odd number we cann't reshape the array values"

ValueError: cannot reshape array of size 7 into shape (2,3)

In [87]:
abc.resize(2,3)

In [88]:
abc

array([[10, 50, 60],
       [70, 80, 90]])

In [90]:
abc4 = np.array([[10,20,30,40],[50,60,70,80]])

In [91]:
abc4

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [93]:
abc4.reshape(4,2)

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [94]:
salary = np.array([1000,2000,3000,4000,6000,10000])

In [95]:
salary

array([ 1000,  2000,  3000,  4000,  6000, 10000])

In [97]:
abc5 = np.where(salary>5000, True, False)

In [98]:
abc5

array([False, False, False, False,  True,  True])

In [99]:
abc5 = np.where(salary>5000, "yes", "No")

In [100]:
abc5

array(['No', 'No', 'No', 'No', 'yes', 'yes'], dtype='<U3')

In [101]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [104]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])