In [1]:
import numpy as np
import pandas as pd

In [2]:
fb = pd.read_csv(r"C:\Users\Balakrishna_Vema\Documents\Data science\Data sets\Fiberbits_v1.csv")

In [3]:
fb.head()

active_cust  income  months_on_network  Num_complaints  \
0            0    1586                 85               4   
1            0    1581                 85               4   
2            0    1594                 82               4   
3            0    1594                 82               4   
4            1    1609                 80               4   

   number_plan_changes  relocated  monthly_bill  technical_issues_per_month  \
0                    1          0           121                           4   
1                    1          0           133                           4   
2                    1          0           118                           4   
3                    1          0           123                           4   
4                    1          0           177                           4   

   Speed_test_result  
0                 85  
1                 85  
2                 85  
3                 85  
4                 85

In [4]:
#Minmax scaller 
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()
fb1 = pd.DataFrame(mm.fit_transform(fb), columns=fb.columns)

In [5]:
fb1.head()

active_cust    income  months_on_network  Num_complaints  \
0          0.0  0.001994           0.223881        0.333333   
1          0.0  0.001972           0.223881        0.333333   
2          0.0  0.002029           0.217484        0.333333   
3          0.0  0.002029           0.217484        0.333333   
4          1.0  0.002095           0.213220        0.333333   

   number_plan_changes  relocated  monthly_bill  technical_issues_per_month  \
0             0.111111        0.0      0.602649                         0.5   
1             0.111111        0.0      0.682119                         0.5   
2             0.111111        0.0      0.582781                         0.5   
3             0.111111        0.0      0.615894                         0.5   
4             0.111111        0.0      0.973510                         0.5   

   Speed_test_result  
0               0.05  
1               0.05  
2               0.05  
3               0.05  
4               0.05

In [7]:
from sklearn.decomposition import PCA
pa=PCA()
pa.fit(fb1)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [8]:
pa.explained_variance_ratio_

array([5.04979273e-01, 2.01199125e-01, 1.68157860e-01, 7.10825867e-02,
       3.27423139e-02, 1.62696203e-02, 2.74227534e-03, 2.57551232e-03,
       2.51433791e-04])

In [9]:
pa.explained_variance_

array([2.77605966e-01, 1.10606673e-01, 9.24426557e-02, 3.90767527e-02,
       1.79996728e-02, 8.94401794e-03, 1.50753117e-03, 1.41585531e-03,
       1.38222546e-04])

In [11]:
pa.n_components_

9

In [12]:
pa.n_samples_

100000

In [13]:
pa.singular_values_

array([166.61428219, 105.16918142,  96.14662308,  62.51108855,
        42.42580912,  29.90640149,  12.27809471,  11.89891236,
         3.71781069])

In [14]:
pa.explained_variance_ratio_

array([5.04979273e-01, 2.01199125e-01, 1.68157860e-01, 7.10825867e-02,
       3.27423139e-02, 1.62696203e-02, 2.74227534e-03, 2.57551232e-03,
       2.51433791e-04])

In [15]:
pa.explained_variance_

array([2.77605966e-01, 1.10606673e-01, 9.24426557e-02, 3.90767527e-02,
       1.79996728e-02, 8.94401794e-03, 1.50753117e-03, 1.41585531e-03,
       1.38222546e-04])

In [16]:
pa.mean_

array([0.57859   , 0.00317144, 0.1671694 , 0.33761333, 0.15393444,
       0.12348   , 0.43587053, 0.38612167, 0.03718669])

In [17]:
from sklearn.decomposition import PCA
pa=PCA(n_components=5)
pa.fit(fb1)

PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [18]:
pa.explained_variance_

array([0.27760597, 0.11060667, 0.09244266, 0.03907675, 0.01799967])

In [20]:
from sklearn.decomposition import PCA

In [21]:
pca= PCA()
pca1 = pc