In [4]:
import pandas as pd
pd.__version__

'0.25.1'

In [2]:
pd?

In [5]:
import numpy as np

In [5]:
#Pandas Series object :A pandas series object is one dimentional array of indexed data. 
#it can be created list or array as follows:
data = pd.Series([0.23,0.34,0.45,0.56])
data

0    0.23
1    0.34
2    0.45
3    0.56
dtype: float64

In [8]:
data.values

array([0.23, 0.34, 0.45, 0.56])

In [9]:
#Index is an array like object of type pd.
data.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
#like numpy array, data can be accessed by the associated index via familier python [] brakets 
data[1]

0.34

In [11]:
data[1:3]

1    0.34
2    0.45
dtype: float64

In [12]:
data = pd.Series([1,2,3,4,5,6], index=['a','b','c','d','e','f'])

In [13]:
data

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [16]:
data['a']

1

In [118]:
#dictionary 
population = {'califonia': 38893,
           'Texas': 998383,
           'Florida': 60373,
           'Illonia':128877}

In [40]:
population = pd.Series(pop_dict)

In [41]:
type(population)

pandas.core.series.Series

In [42]:
population

califonia     38893
Texas        998383
Florida       60373
Illonia      128877
dtype: int64

In [43]:
population['califonia']

38893

In [44]:
population['califonia':'Illonia']

califonia     38893
Texas        998383
Florida       60373
Illonia      128877
dtype: int64

In [45]:
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [46]:
pd.Series([1,2,3,4], index=[100,200,300,400])

100    1
200    2
300    3
400    4
dtype: int64

In [47]:
pd.Series(4, index=[100,200,300])

100    4
200    4
300    4
dtype: int64

In [48]:
pd.Series({2:'a',1:'b',3:'c'})

2    a
1    b
3    c
dtype: object

In [49]:
pd.Series({2:'a',1:'b',3:'c'}, index=[1,2])

1    b
2    a
dtype: object

In [53]:
area_dict = {'califonia': 9900,
           'Texas': 88999,
           'Florida': 89988,
           'Illonia':777627}

In [54]:
area = pd.Series(area_dict)

In [55]:
area

califonia      9900
Texas         88999
Florida       89988
Illonia      777627
dtype: int64

In [56]:
states = pd.DataFrame({'population':population,'area':area})

In [57]:
states

population    area
califonia       38893    9900
Texas          998383   88999
Florida         60373   89988
Illonia        128877  777627

In [58]:
states.index

Index(['califonia', 'Texas', 'Florida', 'Illonia'], dtype='object')

In [59]:
states.columns

Index(['population', 'area'], dtype='object')

In [60]:
states['area']

califonia      9900
Texas         88999
Florida       89988
Illonia      777627
Name: area, dtype: int64

In [64]:
pd.DataFrame(population, columns=['population'])

population
califonia       38893
Texas          998383
Florida         60373
Illonia        128877

In [66]:
data = [{'a':i, 'b':2*i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [67]:
pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [68]:
pd.DataFrame(np.random.rand(3,2),
            columns=['far','bar'],
            index=['a','b','c'])

far       bar
a  0.981431  0.739720
b  0.850054  0.564010
c  0.889318  0.678648

In [75]:
A = np.zeros(3, dtype=[('A', 'i8'),('B','f8')])

In [76]:
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [78]:
indA = pd.Index([1,2,3,4])

In [79]:
indA

Int64Index([1, 2, 3, 4], dtype='int64')

In [80]:
indB = ([2,3,5,6])

In [81]:
indA&indB

Int64Index([2, 3], dtype='int64')

In [82]:
type(indA)

pandas.core.indexes.numeric.Int64Index

In [90]:
data = pd.Series(range(20,25), index=['a','b','c','d','e'])

In [91]:
data

a    20
b    21
c    22
d    23
e    24
dtype: int64

In [92]:
data['b']

21

In [93]:
'a' in data

True

In [94]:
data.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [98]:
data['f'] =26

In [99]:
data

a    20
b    21
c    22
d    23
e    24
f    26
dtype: int64

In [102]:
data1 = pd.Series(range(20,25), index=(range(1,6)))

In [103]:
data1

1    20
2    21
3    22
4    23
5    24
dtype: int64

In [104]:
#making 
data((data>20)& (data<25) )

TypeError: 'Series' object is not callable

In [120]:
#Data selection in Data frame
import pandas as pd
area = pd.Series({"California":423967,"Texas":695662,"NewYork":14129,"Florida":170312,"Illinois":149995})
pop = pd.Series({"California":38332521,"Texas":26448193,"NewYork":19651127,"Florida":19552860,"Illinois":12882135})

In [123]:
data = pd.DataFrame({"area":area,"pop":pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
NewYork      14129  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [124]:
data['area']

California    423967
Texas         695662
NewYork        14129
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [125]:
data.area

California    423967
Texas         695662
NewYork        14129
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [126]:
data.area is data["area"]

True

In [128]:
data.pop is data["area"] #this function usefull only string values 

False

In [133]:
data["pop"] = pop

In [134]:
data

area       pop
California  423967  38332521
Texas       695662  26448193
NewYork      14129  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [135]:
#Add a new coloum
data["density"] = data["pop"]/data["area"]

In [149]:
data

area       pop      density
California  423967  38332521    90.413926
Texas       695662  26448193    38.018740
NewYork      14129  19651127  1390.836365
Florida     170312  19552860   114.806121
Illinois    149995  12882135    85.883763

In [138]:
data.T

California         Texas       NewYork       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412900e+04  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390836e+03  1.148061e+02  8.588376e+01

In [139]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [140]:
#passing single index to dataframe accesses a column:
data["area"]

California    423967
Texas         695662
NewYork        14129
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [141]:
data

area       pop      density
California  423967  38332521    90.413926
Texas       695662  26448193    38.018740
NewYork      14129  19651127  1390.836365
Florida     170312  19552860   114.806121
Illinois    149995  12882135    85.883763

In [145]:
data

area       pop      density
California  423967  38332521    90.413926
Texas       695662  26448193    38.018740
NewYork      14129  19651127  1390.836365
Florida     170312  19552860   114.806121
Illinois    149995  12882135    85.883763

In [146]:
data1 = data

In [147]:
data1

area       pop      density
California  423967  38332521    90.413926
Texas       695662  26448193    38.018740
NewYork      14129  19651127  1390.836365
Florida     170312  19552860   114.806121
Illinois    149995  12882135    85.883763

In [171]:
data1.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
NewYork      14129  19651127

In [191]:
data1.loc[:,:"area"]

area
California  423967
Texas       695662
NewYork      14129
Florida     170312
Illinois    149995

In [197]:
data1.ix[::-2,:"pop"]

C:\Users\Balakrishna_Vema\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


area       pop
Illinois    149995  12882135
NewYork      14129  19651127
California  423967  38332521

In [198]:
data1

area       pop      density
California  423967  38332521    90.413926
Texas       695662  26448193    38.018740
NewYork      14129  19651127  1390.836365
Florida     170312  19552860   114.806121
Illinois    149995  12882135    85.883763

In [199]:
data1.loc[data1.density>100,['pop','density']]

pop      density
NewYork  19651127  1390.836365
Florida  19552860   114.806121

In [200]:
data1.loc[data1.density<100]

area       pop    density
California  423967  38332521  90.413926
Texas       695662  26448193  38.018740
Illinois    149995  12882135  85.883763

In [207]:
#we can modify the data by using the loc or iloc ex:
data1.iloc[0,2] = 90

In [215]:
data1

area       pop      density
California  423967  38332521    90.000000
Texas       695662  26448193    38.018740
NewYork      14129  19651127  1390.836365
Florida     170312  19552860   114.806121
Illinois    149995  12882135    85.883763

In [223]:
data1.loc[:'California',"density"] = 99

In [224]:
data1

area       pop      density
California  423967  38332521    99.000000
Texas       695662  26448193    38.018740
NewYork      14129  19651127  1390.836365
Florida     170312  19552860   114.806121
Illinois    149995  12882135    85.883763

In [225]:
data1

area       pop      density
California  423967  38332521    99.000000
Texas       695662  26448193    38.018740
NewYork      14129  19651127  1390.836365
Florida     170312  19552860   114.806121
Illinois    149995  12882135    85.883763

In [226]:
data1["Florida":"Illinois"]

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [236]:
data1[3:5]

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [237]:
data1[data1.density>50]

area       pop      density
California  423967  38332521    99.000000
NewYork      14129  19651127  1390.836365
Florida     170312  19552860   114.806121
Illinois    149995  12882135    85.883763

In [242]:
rng = np.random.RandomState(42)
rng

In [243]:
ser = pd.Series(rng.randint(0,10,4))

In [244]:
ser

0    6
1    3
2    7
3    4
dtype: int32

In [246]:
df = pd.DataFrame(rng.randint(0,10,(3,4)), columns=['a','b','c','d'])

In [247]:
df

a  b  c  d
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [248]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [254]:
#Handling missing data
#1.None in Numpy
vals1 = np.array([1,None,3,4])

In [255]:
vals1  #in numpy if you add "None" value it will consider that araay as object dtype

array([1, None, 3, 4], dtype=object)

In [262]:
for dtype in ['object', 'int']:
    print("dtype=", dtype)
    

dtype= object
dtype= int


In [263]:
#2.NaN(Not a number) in Numpay
vals2 = np.array([1,np.nan,3,4])

In [265]:
vals2.dtype

dtype('float64')

In [268]:
1+np.nan

nan

In [269]:
1*np.nan

nan

In [270]:
vals2.sum()

nan

In [271]:
vals2.min()

nan

In [272]:
vals2.max()

nan

In [273]:
#Numpy provide some sepcifci aggregation for the Nan values like below 
np.nanmax(vals2)

4.0

In [274]:
np.nanmin(vals2)

1.0

In [276]:
np.nanmedian(vals2)

3.0

In [277]:
#Nan & None in pandas 
pd.Series([1,np.nan,3,None])

0    1.0
1    NaN
2    3.0
3    NaN
dtype: float64

In [278]:
x = pd.Series(range(2), dtype='int')

In [279]:
x

0    0
1    1
dtype: int32

In [280]:
x[0]=None

In [281]:
x

0    NaN
1    1.0
dtype: float64

In [284]:
#Operating on Null Values 
#1. isnull(): Generate the boolean mask indicating missing values
#2. notnull(): opposite of isnull()
#3. dropna(): returened filliet varsion of data
#4. fillna():Return a copy of datawith missing values filled or imputed

In [314]:
#isnull()
data = pd.Series([1,np.nan,3,None,"hello"])

In [315]:
data.isnull()

0    False
1     True
2    False
3     True
4    False
dtype: bool

In [316]:
data.notnull()

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [318]:
data[data.notnull()]

0        1
2        3
4    hello
dtype: object

In [320]:
data

0        1
1      NaN
2        3
3     None
4    hello
dtype: object

In [321]:
data.dropna()

0        1
2        3
4    hello
dtype: object

In [326]:
df = pd.DataFrame([[1,np.nan,2],[2,3,5],[np.nan,4,6]],columns=(["a","b","c"]))

In [327]:
df

a    b  c
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [328]:
df.dropna()

a    b  c
1  2.0  3.0  5

In [330]:
df.dropna(axis="columns")

c
0  2
1  5
2  6

In [331]:
df["d"] = np.nan

In [332]:
df

a    b  c   d
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [333]:
df.dropna(axis=1,how="all")

a    b  c
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [335]:
df.dropna(how="any",axis=1)

c
0  2
1  5
2  6

In [336]:
df

a    b  c   d
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [341]:
df["e"] = [1,np.nan,np.nan]

In [342]:
df

a    b  c   d    e
0  1.0  NaN  2 NaN  1.0
1  2.0  3.0  5 NaN  NaN
2  NaN  4.0  6 NaN  NaN

In [344]:
df.dropna(axis=1, thresh=2)

a    b  c
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [346]:
df.dropna(axis=0,thresh=3)

a    b  c   d    e
0  1.0  NaN  2 NaN  1.0
1  2.0  3.0  5 NaN  NaN

In [347]:
df

a    b  c   d    e
0  1.0  NaN  2 NaN  1.0
1  2.0  3.0  5 NaN  NaN
2  NaN  4.0  6 NaN  NaN

In [350]:
df1 = df.fillna(0)

In [353]:
df1[df1.notnull()]

a    b  c    d    e
0  1.0  0.0  2  0.0  1.0
1  2.0  3.0  5  0.0  0.0
2  0.0  4.0  6  0.0  0.0

In [354]:
df

a    b  c   d    e
0  1.0  NaN  2 NaN  1.0
1  2.0  3.0  5 NaN  NaN
2  NaN  4.0  6 NaN  NaN

In [355]:
# # forward-fill
df.fillna(method="ffill")

a    b  c   d    e
0  1.0  NaN  2 NaN  1.0
1  2.0  3.0  5 NaN  1.0
2  2.0  4.0  6 NaN  1.0

In [356]:
##back-fill
df.fillna(method="bfill")

a    b  c   d    e
0  1.0  3.0  2 NaN  1.0
1  2.0  3.0  5 NaN  NaN
2  NaN  4.0  6 NaN  NaN

In [358]:
#Hierarchical Indexing
index = [('california',2000),('califonina',2010),
        ('New york',2000),('New york',2010),
        ('Texas',2000),('Texas',2010)]
population = [33871648,37253956,
             18976457,19378102,
             20851820,25145561]

In [359]:
pop = pd.Series(population, index=index)

In [360]:
pop

(california, 2000)    33871648
(califonina, 2010)    37253956
(New york, 2000)      18976457
(New york, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [361]:
#Combining Datasets: Concat and Append
#numpy concatinate
x =[1,2,3]
y=[2,3,4]
z=[4,5,6]

In [362]:
np.concatenate([x,y,z])

array([1, 2, 3, 2, 3, 4, 4, 5, 6])

In [369]:
x=[[1,2],[2,4]]
dd= np.concatenate([x,x],axis=1)

In [370]:
pd.DataFrame(dd)

0  1  2  3
0  1  2  1  2
1  2  4  2  4

In [375]:
ser1 = pd.Series(['A','B','C','D'], index=[1,2,3,4])

In [376]:
ser1

1    A
2    B
3    C
4    D
dtype: object

In [377]:
ser2= pd.Series(['E','F'], index=[5,6])

In [378]:
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [380]:
df1 = pd.DataFrame(ser1)
df2 = pd.DataFrame(ser2)

In [382]:
pd.concat([df1,df2], axis=1)

0    0
1    A  NaN
2    B  NaN
3    C  NaN
4    D  NaN
5  NaN    E
6  NaN    F

In [390]:
#merge
df1 = pd.DataFrame({"employee":['bob','jake','lisa','sue'],
                    "group":['Accounting','Engineering','Engineering','HR']})
df2 = pd.DataFrame({"employee":['lisa','bob','jake','sue'],
                    "hire_date":[2004,2008,2012,2014]})

In [401]:
df3 = pd.merge(df1,df2)

In [402]:
df3

employee        group  hire_date
0      bob   Accounting       2008
1     jake  Engineering       2012
2     lisa  Engineering       2004
3      sue           HR       2014

In [406]:
df4 = pd.DataFrame({"group":['Accounting','Engineering','HR'],
                   'superviosr':['Carly','gudio','Stev']})

In [407]:
df4

group superviosr
0   Accounting      Carly
1  Engineering      gudio
2           HR       Stev

In [408]:
df5=pd.merge(df3,df4)

In [409]:
df5

employee        group  hire_date superviosr
0      bob   Accounting       2008      Carly
1     jake  Engineering       2012      gudio
2     lisa  Engineering       2004      gudio
3      sue           HR       2014       Stev

In [412]:
df6 = pd.DataFrame({"group":['Accounting','Accounting','Engineering','Engineering','HR','HR'],
                    "skills":['math','spreadsheet','coding','linux',
                             'spreadsheet','organization']})

In [413]:
df6

group        skills
0   Accounting          math
1   Accounting   spreadsheet
2  Engineering        coding
3  Engineering         linux
4           HR   spreadsheet
5           HR  organization

In [415]:
pd.merge(df1,df6)

employee        group        skills
0      bob   Accounting          math
1      bob   Accounting   spreadsheet
2     jake  Engineering        coding
3     jake  Engineering         linux
4     lisa  Engineering        coding
5     lisa  Engineering         linux
6      sue           HR   spreadsheet
7      sue           HR  organization

In [432]:
df3 = pd.DataFrame({"name":['bob','jake','lisa','sue'],
                   'salary':[70000,80000,120000,90000]})

In [433]:
df3

name  salary
0   bob   70000
1  jake   80000
2  lisa  120000
3   sue   90000

In [434]:
pd.merge(df1,df3,left_on='employee',right_on='name')

employee        group  name  salary
0      bob   Accounting   bob   70000
1     jake  Engineering  jake   80000
2     lisa  Engineering  lisa  120000
3      sue           HR   sue   90000

In [435]:
pd.merge(df1,df3,left_on='employee',right_on='name').drop(columns='name').

employee        group  salary
0      bob   Accounting   70000
1     jake  Engineering   80000
2     lisa  Engineering  120000
3      sue           HR   90000

In [6]:
df6 = pd.DataFrame({'name':['peter','paul','mary'],
               'food':['fish','beans','bread']},
                 columns=['name','food'])
df7 = pd.DataFrame({'name':['mary','joseph'],
               'drink':['wine','beer']},
                 columns=['name','drink'])

In [8]:
print(pd.merge(df6,df7))

   name   food drink
0  mary  bread  wine


In [9]:
print(pd.merge(df6,df7,how='outer'))

     name   food drink
0   peter   fish   NaN
1    paul  beans   NaN
2    mary  bread  wine
3  joseph    NaN  beer


In [12]:
print(pd.merge(df6,df7,how='left'))

    name   food drink
0  peter   fish   NaN
1   paul  beans   NaN
2   mary  bread  wine


In [17]:
df8 = pd.DataFrame({'name':['bob','jake','lisa','sue'],
                    'rank':[1,2,3,4]})

In [18]:
df9 = pd.DataFrame({'name':['bob','jake','lisa','sue'],
                    'rank':[3,1,4,2]})

In [19]:
print(pd.merge(df8,df9, on='name'))

   name  rank_x  rank_y
0   bob       1       3
1  jake       2       1
2  lisa       3       4
3   sue       4       2


In [20]:
print(pd.merge(df8,df9, on='name', suffixes=["-L","_R"]))

   name  rank-L  rank_R
0   bob       1       3
1  jake       2       1
2  lisa       3       4
3   sue       4       2
