In [1]:
import numpy as np
import pandas as pd

In [2]:
a1=np.array([1,None,3,4])

In [3]:
a1

array([1, None, 3, 4], dtype=object)

In [4]:
ab=np.array([1,2,3,4])

In [5]:
ab

array([1, 2, 3, 4])

In [8]:
a2=np.array([1,np.nan,3,4])

In [9]:
a2

array([ 1., nan,  3.,  4.])

In [10]:
a3=np.array(['india', np.nan,'aus'])

In [11]:
a3.dtype

dtype('<U5')

In [12]:
a3=np.array(['india', None,'aus'])

In [13]:
a3

array(['india', None, 'aus'], dtype=object)

In [14]:
1+np.nan

nan

In [15]:
0*np.nan

nan

In [16]:
a2.sum()

nan

In [17]:
a2.min()

nan

In [18]:
np.nansum(a2)

8.0

In [19]:
np.sum(a2)

nan

In [20]:
np.nanmax(a2)

4.0

In [21]:
np.nanmin(a2)

1.0

In [22]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [23]:
x=pd.Series(range(2), dtype=int)

In [24]:
x

0    0
1    1
dtype: int32

In [25]:
x[0]=None

In [26]:
x

0    NaN
1    1.0
dtype: float64

In [27]:
ab=pd.Series([1,np.nan,"hello",None])

In [28]:
ab

0        1
1      NaN
2    hello
3     None
dtype: object

In [29]:
ab.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [30]:
ab.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [31]:
ab[ab.notnull()]

0        1
2    hello
dtype: object

In [32]:
ab.dropna()

0        1
2    hello
dtype: object

In [35]:
df=pd.DataFrame([[1,np.nan,2],[2,3,5],[np.nan,4,6]])

In [36]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [38]:
df.dropna() #will drop all rows in which any null values present of the given data

0    1  2
1  2.0  3.0  5

In [39]:
df=pd.DataFrame([[1,np.nan,2],[2,3,5],[np.nan,4,6]])

In [40]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [41]:
df1 = df.dropna(axis='columns') #if perticular column is most NA values we can use this 

In [42]:
df1

2
0  2
1  5
2  6

In [43]:
df=pd.DataFrame([[1,np.nan,2],[2,3,5],[np.nan,4,6]])

In [95]:
df=pd.DataFrame()

In [96]:
df

Empty DataFrame
Columns: []
Index: []

In [97]:
df[0]=[1,2,np.nan]

In [98]:
df

0
0  1.0
1  2.0
2  NaN

In [99]:
df[1]=[np.nan,3,4]
df[2]=[2,5,6]

In [100]:
df[3]=np.nan

In [101]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [51]:
df1=df.dropna(axis="columns",how="all")
df1

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [52]:
df1=df.dropna(axis="columns",thresh=3)
df1

2
0  2
1  5
2  6

In [86]:
df

[1, nan, nan, nan]

In [61]:
df1=df.dropna(axis="columns",thresh=1)

In [84]:
df[4]=[1,np.nan,np.nan]
df1=[1,np.nan, np.nan,np.nan]


IndexError: list assignment index out of range

In [75]:
df1=df.dropna(axis="rows",thresh=3)

In [103]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [105]:
data=pd.Series([1,np.nan,2,None,3], index=list("abcde"))

In [106]:
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [107]:
data.isnull()

a    False
b     True
c    False
d     True
e    False
dtype: bool

In [108]:
data1=data.fillna(0)

In [109]:
data1

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [110]:
data1=data.fillna(method="ffill")#it will replace the perfvious value

In [111]:
data1=data.fillna(method="bfill")

In [112]:
data1

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [113]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [114]:
df1=df.fillna(method="ffill",axis=1)#colum level 

In [115]:
df1

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [116]:
df1=df.fillna(method="ffill",axis=0)#colum level 

In [117]:
df1

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  2.0  4.0  6 NaN

In [120]:
df1=df.fillna(0)

In [121]:
df1

0    1  2    3
0  1.0  0.0  2  0.0
1  2.0  3.0  5  0.0
2  0.0  4.0  6  0.0

In [124]:
from sklearn.impute import SimpleImputer #mission learning the module, there we have diferent sub packages are there 
my_imputer = SimpleImputer()#it calculate the avarge value 
df1=pd.DataFrame(my_imputer.fit_transform(df))# it will add the avarage value for columns level 

In [125]:
df1

0    1    2
0  1.0  3.5  2.0
1  2.0  3.0  5.0
2  1.5  4.0  6.0

In [126]:
bill=pd.read_csv(r"C:\Users\Balakrishna_Vema\Documents\Data science\Data sets\Bill (1).csv")

In [127]:
bill

cust_id act_active_dt  package_id  bill_zip customer_segment  status  \
0     9243148228     6/22/2006     54518.0    560095                S  ACTIVE   
1     9243264060     6/23/2006    617691.0    580029                S  ACTIVE   
2     8951061271     8/14/2010    616488.0    560037                F  ACTIVE   
3     8951033996     6/26/2010    616488.0    560062                R  ACTIVE   
4     9241079722     9/30/2005    614975.0    560017           G - TC  ACTIVE   
...          ...           ...         ...       ...              ...     ...   
9457  9243300397      7/9/2011    618381.0    560070                B  ACTIVE   
9458  9243300657      7/9/2011    615031.0    560043                B  ACTIVE   
9459  9243301205     7/12/2011    618403.0    560016                B  ACTIVE   
9460  9243500761     7/13/2011    629978.0    560100                B  ACTIVE   
9461  9243306488     7/13/2011    618381.0    560047                B  ACTIVE   

      bill_amt  
0       561.80  
1       224.35  
2      1689.04  
3       344.04  
4       478.33  
...        ...  
9457   1106.18  
9458    674.16  
9459    772.02  
9460    842.70  
9461    477.53  

[9462 rows x 7 columns]

In [129]:
bill.shape

(9462, 7)

In [130]:
bill.dtypes

cust_id               int64
act_active_dt        object
package_id          float64
bill_zip              int64
customer_segment     object
status               object
bill_amt            float64
dtype: object

In [131]:
def miss_identify(data):
    return data.isnull().sum()/len(data)*100

In [132]:
miss_identify(bill)

cust_id             0.000000
act_active_dt       0.000000
package_id          0.063412
bill_zip            0.000000
customer_segment    1.099133
status              0.000000
bill_amt            0.000000
dtype: float64

In [133]:
from sklearn.impute import SimpleImputer
ss=SimpleImputer()


In [135]:
myfile = open(r"C:\Users\Balakrishna_Vema\Documents\Data science\Data sets\Bill (1).csv").read()
print(type(myfile))

<class 'str'>
